def get_dosage(medicine_name: str) -> str:
    dosage_map = {
    "Paracetamol": "500 mg every 6 hours (max 4 doses in 24 hours)",
    "Cetirizine": "10 mg once daily (preferably at night)",
    "Dolo 650": "650 mg every 6–8 hours as needed",
    "Crocin": "500 mg every 6 hours for adults",
    "ORS Sachets": "1 sachet in 1 litre of water, sip throughout the day",
    "Ondansetron": "4–8 mg every 8 hours for nausea or vomiting",
    "Benadryl": "2 tsp (10 ml) every 4–6 hours, max 4 times/day",
    "Cyclopam": "1 tablet after meals, up to 3 times a day",
    "Gelusil": "2 tsp after meals and at bedtime",
    "Lactulose": "15–30 ml once or twice daily",
    "Digene": "2 tsp after meals and at bedtime",
    "Levocetirizine": "5 mg once daily at bedtime",
    "Domperidone": "10 mg 2–3 times before meals",
    "Volini": "Apply topically 3–4 times a day",
    "Ciplox Eye Drops": "1–2 drops 4 times a day",
    "Otogesic": "4–5 drops in ear 2–3 times a day",
    "Candid B Cream": "Apply twice daily on affected area",
    "Brufen": "400 mg every 6–8 hours as needed",
    "Mefkind Forte": "1 tablet after meals, max 2/day",
    "Azithromycin": "Take 500 mg once daily for 3 days.",
    "Alprazolam": "0.25 mg to 0.5 mg three times daily as needed.",
    "Clonazepam": "0.5 mg twice daily. Adjust as per medical advice.",
    "Citalopram": "20 mg once daily.",
    "Escitalopram": "10 mg once daily.",
    "Duloxetine": "30 to 60 mg once daily.",
    "Amitriptyline": "25 mg at bedtime. Adjust based on response.",
    "Buspirone": "5 mg two to three times daily.",
    "Bupropion": "150 mg once daily in the morning.",
    "Doxycycline": "100 mg twice daily for 7–14 days.",
    "Celexa": "20 mg once daily.",
    "Cymbalta": "30 mg to 60 mg once daily.",
    "Effexor XR": "75 mg once daily with food.",
    "Zoloft": "50 mg once daily.",
    "Sertraline": "50 mg once daily.",
    "Paroxetine": "20 mg once daily in the morning.",
    "Ibuprofen": "400 mg every 4 to 6 hours as needed.",
    "Levothyroxine": "25 mcg to 100 mcg once daily on an empty stomach.",
    "Metformin": "500 mg twice daily with meals.",
    "Trazodone": "150 mg daily in divided doses.",
    "Venlafaxine": "75 mg/day in divided doses.",
    "Fluoxetine": "20 mg once daily in the morning.",
    "Gabapentin": "300 mg once daily initially, then titrate as needed.",
    "Prednisone": "5 mg to 60 mg once daily depending on condition.",
    "Hydrochlorothiazide": "25 mg once daily.",
    "Abilify": "Dosage information not available. Please consult your doctor.",
    "Acetaminophen / hydrocodone": "Dosage information not available. Please consult your doctor.",
    "Acetaminophen / oxycodone": "Dosage information not available. Please consult your doctor.",
    "Adapalene / benzoyl peroxide": "Dosage information not available. Please consult your doctor.",
    "Alprazolam": "0.25 mg to 0.5 mg three times daily as needed.",
    "Amitriptyline": "25 mg at bedtime. Adjust based on response.",
    "Amphetamine / dextroamphetamine": "Dosage information not available. Please consult your doctor.",
    "Aripiprazole": "Dosage information not available. Please consult your doctor.",
    "Azithromycin": "Take 500 mg once daily for 3 days.",
    "Belviq": "Dosage information not available. Please consult your doctor.",
    "Bisacodyl": "Dosage information not available. Please consult your doctor.",
    "Buprenorphine / naloxone": "Dosage information not available. Please consult your doctor.",
    "Bupropion": "150 mg once daily in the morning.",
    "Bupropion / naltrexone": "Dosage information not available. Please consult your doctor.",
    "Buspirone": "5 mg two to three times daily.",
    "Celexa": "20 mg once daily.",
    "Citalopram": "20 mg once daily.",
    "Clindamycin": "Dosage information not available. Please consult your doctor.",
    "Clonazepam": "0.5 mg twice daily. Adjust as per medical advice.",
    "Cymbalta": "30 mg to 60 mg once daily.",
    "Doxycycline": "100 mg twice daily for 7–14 days.",
    "Duloxetine": "30 to 60 mg once daily.",
    "Effexor XR": "75 mg once daily with food.",
    "Escitalopram": "10 mg once daily.",
    "Ethinyl estradiol / etonogestrel": "10 to 50 mcg orally once a day",
    "Gabapentin": "300 mg once daily initially, then titrate as needed.",
    "Sertraline": "50 mg once daily.",
    "Paroxetine": "20 mg once daily in the morning.",
    "Fluoxetine": "20 mg once daily in the morning.",
    "Metformin": "500 mg twice daily with meals.",
    "Trazodone": "150 mg daily in divided doses.",
    "Levothyroxine": "25 mcg to 100 mcg once daily on an empty stomach.",
    "Prednisone": "5 mg to 60 mg once daily depending on condition.",
    "Hydrochlorothiazide": "25 mg once daily.",
    "Ibuprofen": "400 mg every 4 to 6 hours as needed.",
    "Venlafaxine": "75 mg/day in divided doses.",
    "Zoloft": "50 mg once daily.",
    "Rest of the medicines": "Dosage information not available. Please consult your doctor.",
    "Ethinyl estradiol / norgestimate": "10 to 50 mcg orally once a day."
}
    return dosage_map.get(medicine_name, "Dosage not available. Please consult with a doctor for the dosage.")
